name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "43.218.77.16:443"
UUID = "c5f7c156-2d6d-4b64-a7ff-6abb19eb9840"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
