name = "xuts"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern = "xuts.dakona.my.id"
custom_domain = true

[vars]
PROXYIP = "110.34.164.39:28758"
UUID = "99cead74-3895-488a-af5b-58fefaff97bb"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
