name = "au"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern = "au.dakona.my.id"
custom_domain = true

[vars]
PROXYIP = "97.74.82.87:45837"
UUID = "d5a09c3b-7cef-44ac-97c6-4b5e9377bb8f"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
